title: LeFizzim's World
description: Fun ideas that have been brought to life in code
url: "https://lefizzim.github.io"
author: LeFizzim
theme: jekyll-theme-midnight
logo: /assets/images/logo.png
image: /assets/images/logo.png
